### ISSUE TITLE
Willing to make licence GPL compatable?

### ISSUE THREAD

**Issue by jackhill** [brendanhay/ede#13]
After reading http://www.gnu.org/licenses/license-list.html#MPL-2.0 I'm unsure if the "Incompatible With Secondary Licenses" notice would preclude me from depending on ED-E in my GPL application. Did you include this notice for a reason? If not would you be willing to remove it?

**Comment by brendanhay** [comment]
Thanks for raising this. It is in fact an artifact from another project's license file, I'll remove it and do a point release.

**Comment by jackhill** [comment]
Cool, thanks!
