### ISSUE TITLE
Missing documentation for filters

### ISSUE THREAD

**Issue by utdemir** [brendanhay/ede#16]
Hi,

There are filters implemented at [Text.Ede.Internal.Filters](https://github.com/brendanhay/ede/blob/develop/src/Text/EDE/Internal/Filters.hs), but some of them are't included on the documentation:  [Text.Ede.Filters](https://github.com/brendanhay/ede/blob/develop/src/Text/EDE/Filters.hs).

I intend to just add the missing filters to documentation and make a PR, but I thought that maybe you have a reason for not including them (backward-compatibility etc), so I wanted to ask first.

So, is there any reason for not documenting some filters?

**Comment by brendanhay** [comment]
No reason other than the filters were merged from another project's extensions into the core library, without any documentation.

**Comment by brendanhay** [comment]
Fixed on `main`.
