### ISSUE TITLE
<command line>: can't load .so/.DLL for: stdc++.dll

### ISSUE THREAD

**Issue by reygoch** [brendanhay/ede#20]
Can't build ede on Windows. I'm getting following error :

```
C:\Users\reygoch\Desktop\cervantes>stack build
cervantes-0.1.0.0: unregistering (missing dependencies: ede)
ede-0.2.8.4: configure
ede-0.2.8.4: build
Progress: 1/2
--  While building package ede-0.2.8.4 using:
      C:\sr\setup-exe-cache\x86_64-windows\setup-Simple-Cabal-1.22.5.0-ghc-7.10.3.exe --builddir=.stack-work\dist\2672c1f3 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\Users\reygoch\Desktop\cervantes\.stack-work\logs\ede-0.2.8.4.log

    Configuring ede-0.2.8.4...
    Building ede-0.2.8.4...
    Preprocessing library ede-0.2.8.4...
    [ 1 of 10] Compiling Text.EDE.Internal.Types ( src\Text\EDE\Internal\Types.hs, .stack-work\dist\2672c1f3\build\Text\EDE\Internal\Types.o )
    <command line>: can't load .so/.DLL for: stdc++.dll (addDLL: could not load DLL)
    ghc.EXE: stdc++: The specified module could not be found.
```

I'm not sure how to resolve this. `stdc++` should be accessible to the linker but it fails for some reason.

**Comment by brendanhay** [comment]
Hi @reygoch, unfortunately I don't have a Windows machine available to test on. The error is quite ambiguous as there's no funky CPP or abnormal dependencies in `ede`.

Can you try on a different GHC version if possible? The stack file in the root `ede` project is set to use `ghc-8.0.1`.

**Comment by RyanGlScott** [comment]
I'm 90% sure this is caused by the `double-conversion` dependency, which until version version [2.0.2.0](http://hackage.haskell.org/package/double-conversion-2.0.2.0) had a [nasty runtime linker issue](https://github.com/bos/double-conversion/pull/13). If you build `ede` against that version of `double-conversion`, I don't think you'll have this issue.

**Comment by brendanhay** [comment]
Thanks for the info @RyanGlScott, I've added a constraint on the transitive dependency in the hope it'll alleviate the above problem.
