### ISSUE TITLE
Lower bound on prettyprinter (application part only) is too loose

### ISSUE THREAD

**Issue by endgame** [brendanhay/ede#43]
`prettyprinter-1.6.2` does not provide the `Prettyprinter` module, which first appears in `1.7.0` and is imported by the app side (but not the library side) of `ede`.

I can make a PR that raises the lower bound, unless there's some other way you would prefer to handle this?

**Comment by jappeace** [comment]
I did this: https://github.com/brendanhay/ede/pull/45
